#!/bin/bash

# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# Create README.md for the HVX test package

cat > hvx_test_package/README.md << 'EOF'
# Hexagon HVX Test Package

This package contains built HVX (Hexagon Vector eXtensions) example programs with test data.

## Directory Structure

Each subdirectory follows the naming convention:
`HVX_<SDK_VERSION>_<ARCH>_<BUILD_TYPE>/`

Where:
- SDK_VERSION: Hexagon SDK version (e.g., 6.3.0.0)
- ARCH: Hexagon architecture (e.g., v68)
- BUILD_TYPE: Either "asm" (optimized assembly) or "c_ref" (C reference)

Within each directory:
- `bin/` - Executable test programs
- `share/testvectors/` - Input test data files
- `share/golden_outputs/` - Expected output files for validation
- `share/test_outputs/` - Outputs generated during CI build (if available)
- `README.md` - Specific information for that build

## Usage Example

```bash
cd HVX_6.3.0.0_v68_asm/bin
./bilateral.exe 1920 1080 ../share/testvectors/football1920x1080.bin output.bin
```

Generated by GitHub Actions on $(date)
EOF

echo "Package README created successfully"
