#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

coverage() {
    local QEMU_BUILD="$1"
    if test -z "$QEMU_BUILD"
    then
        echo "Error. Please provide the path to a qemu build dir, compiled with gcov."
        echo "To do that, you may run "configure --enable-gcov" at the qemu src."
        echo
        exit 1
    fi
    if test -z "$(find "$QEMU_BUILD" -name '*.gcda')"
    then
        echo "Error: No .gcda files found at QEMU_BUILD (='$QEMU_BUILD')."
        echo "Did you forget to run the test suite?"
        echo
        exit 1
    fi
    (
        cd "$QEMU_BUILD" &&
        find . -name '*.gcda' -print0 \
            | xargs -0 gcov --preserve-paths --branch-probabilities --all-blocks
    )
    mkdir -p coverage
    find "$QEMU_BUILD" -name '*.gcov' -print0 | xargs -0 gcov2perl -db coverage/cover_db
    cover -report html -outputdir coverage/cover_db_html coverage/cover_db
}

case "$1" in
mktags)
    find . -name '*.py' | xargs ctags --python-kinds=+vl -f ./tags
    ;;
coverage)
    coverage "$2"
    ;;
verif)
    shift
    PYTHONPATH="$SCRIPT_DIR" python3 -m src "${@}"
    ;;
*)
    echo "usage: $0 {cmd}"
    echo "  cmds are:"
    echo "  - mktags: create a ctags file"
    echo "  - coverage: create a coverage report after running verif."
    echo "  - verif: main entry point for the verif tool."
    ;;
esac
